create table if not exists "post" (
	"id" int primary key generated by default as identity,
	"title" varchar(64) not null,
	"content" text not null,
	"tags" int[],
	"create_at" timestamptz not null default now()
);

create table if not exists "tag" (
	"id" int primary key generated by default as identity,
	"title" varchar(64) not null unique,
	"create_at" timestamptz not null default now()
);
